# Generated by Django 6.0.5 on 2026-05-06 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Check this to make the song visible to everyone.'),
        ),
    ]
